name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        node-version: '20'

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        node-version: '20'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        node-version: '20'

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./front
        push: true
        tags: tibrook/bobapp-frontend:latest


    - name: Build and push backend Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./back
        push: true
        tags: tibrook/bobapp-backend:latest
