name: Frontend Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests with coverage
      run: npm run test -- --watch=false --browsers=ChromeHeadless

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: frontend-coverage-report
        path: front/coverage

  sonarcloud-analysis:
    runs-on: ubuntu-latest
    needs: test-and-coverage
    defaults:
      run:
        working-directory: front

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install SonarCloud Scanner
      run: npm install -g sonarqube-scanner
      
    - name: Run SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: npx sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=software-developer -Dsonar.projectKey=software-developer_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD-Frontend -Dsonar.host.url=https://sonarcloud.io

  docker:
    runs-on: ubuntu-latest
    needs: test-and-coverage

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./front
        push: true
        tags: tibrook/bobapp-frontend:latest
